BankATM/Controllers/CheckingAccountController.cs
using BankATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankATM.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount
            {
                AccountNumber = "0000123456",
                FirstName = "Kyle",
                LastName = "Ahn",
                Balance = 1000000
            };
            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BankATM/Controllers/HomeController.cs
using BankATM.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankATM.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            return View();
        }

        //GET /home/about
        [ActionName("about-this-atm")]
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having troubles? Please send us a message!";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            //TODO: Send message to HQ
            ViewBag.TheMessage = "Thanks for your participation. We will get back to you as soon as possible!";

            return View();
        }
    }
}

BankATM/Controllers/TransactionController.cs
using BankATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BankATM.Controllers
{
    //lalala
    [Authorize]
    public class TransactionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transaction/Deposit
        public ActionResult Deposit(int checkingAccountId)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Deposit(Transaction transaction)
        {
            if (ModelState.IsValid)
            {

                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

BankATM/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BankATM/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    66 Chancellor Circle<br />
    Winnipeg, MB R3T XXX<br />
    <abbr title="Phone">P:</abbr>
    204.430.XXXX
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">ahns@myumanitoba.ca</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">ahns@myumanitoba.ca</a>
</address>

<h3>@ViewBag.TheMessage</h3>
<form method="post">
    <textarea name="message"></textarea>
    <br />
    <input type="submit" value="Send"/>
</form>

BankATM/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-lg btn-block active"><span class="glyphicon glyphicon-circle-arrow-down"></span>
          Withdrawal</a>
        <a href="#" class="btn btn-primary btn-lg btn-block active">
            <span class="glyphicon glyphicon-usd"></span>
            Quick Cash $200
        </a>
        <a href="@Url.Action("Details","CheckingAccount")" class="btn btn-primary btn-lg btn-block active">
            <span class="glyphicon glyphicon-question-sign"></span>
            Balance Details
        </a>
    </div>

    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-lg btn-block active">
            <span class="glyphicon glyphicon-print"></span>
            Bank Statement
        </a>
        <a href="#" class="btn btn-primary btn-lg btn-block active">
            <span class="glyphicon glyphicon-transfer"></span>
            E-Transfer
        </a>
        <a href="@Url.Action("Deposit", "Transaction", new { checkingAccountId = ViewBag.CheckingAccountId })" class="btn btn-primary btn-lg btn-block active">
            <span class="glyphicon glyphicon-circle-arrow-up"></span>
            Deposit
        </a>
    </div>


</div>